LoginApp.Web/LoginApp.Web/Controllers/AppController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginApp.Web.Controllers
{
    public class AppController : Controller
    {
        //
        // GET: /App/

        public ActionResult Index()
        {
            return View();
        }

    }
}

LoginApp.Web/LoginApp.Web/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginApp.Web.Controllers
{
    public class LoginController : Controller
    {
        //
        // GET: /Login/

        public ActionResult Index()
        {
            return View();
        }

    }
}

LoginApp.Web/LoginApp.Web/Controllers/RegisterController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace LoginApp.Web.Controllers
{
    public class RegisterController : Controller
    {
        //
        // GET: /Register/

        public ActionResult Index()
        {
            return View();
        }

    }
}

LoginApp.Web/LoginApp.Web/Views/Login/login.cshtml
@{
    ViewBag.Title = "login";
    Layout = "~/Views/Shared/_appMaster.cshtml";
}

<h2>Login</h2>
<br />
<br />

<fieldset>
    <legend>Login</legend>
    <br />
    <form id="loginFrm">
        <label>Email : </label>
        <input type="email" name="email" />
        <br />
        <label>Password : </label>
        <input type="password" name="password" />
        <br />
        <br />
        <input type="submit" name="submit" value="Login"/>
        <input type="reset" name="reset" />
    </form>
</fieldset>

<script type="text/javascript">
    $(document).ready(function () {
        $('#loginFrm').on('submit', function (event) {
            $.ajax({
                url: basePath + '',
                type: 'POST',
                data: $(this).serialize(),
                success: function (response) {

                },
                error: function (err) {
                    alert("Error in logging in : " + JSON.stringify(err));
                }
            })
        });
    });
</script>

LoginApp.Web/LoginApp.Web/Views/Register/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_appMaster.cshtml";
}

<br />

<fieldset>
    <legend>Register</legend>
    <form id="registerForm">
        <label>First Name : </label>
        <input type="text" name="firstName" />
        <br />
        <label>Last Name : </label>
        <input type="text" name="lastName" />
        <br />
        <label>Email : </label>
        <input type="email" name="email" />
        <br />
        <label>Password : </label>
        <input type="password" name="password" />
        <br />
        <label>Contact : </label>
        <input type="text" name="mobile" />
        <br />
        <label>Designation : </label>
        <select name="designation">
            <option value="-1">----------------</option>
            <option value="1">Project Manager</option>
            <option value="2">Team Lead</option>
            <option value="3">Sr. Software Engr</option>
            <option value="4">Software Engineer</option>
            <option value="5">Graduate Eng Trainee</option>
        </select>
        <br />
        <label>Date Of Birth : </label>
        <input type="date" name="dob" />
        <br />
        <input type="submit" name="submit" value="Register Me" />
        <input type="reset" value="Clear" />
    </form>
</fieldset>

LoginApp.Web/LoginApp.Web/Views/Shared/_appMaster.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script type="text/javascript">
        basePath = "http://localhost:";
    </script>
</head>
<body>
    <nav>
        <a href="@Url.Action("Index","Login")">Login</a>
        <a href="@Url.Action("Index","Register")">Register</a>
    </nav>
    <div>
        @RenderBody()
    </div>
</body>
</html>