MvcTrainingStart/MvcTrainingStart/Controllers/GalleryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcTrainingStart.Controllers
{
    public class GalleryController : Controller
    {
        //
        // GET: /Gallery/

        public ActionResult gallery()
        {
            return View();
        }

    }
}

MvcTrainingStart/MvcTrainingStart/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcTrainingStart.Controllers
{
    public class HomeController : Controller
    {
        //
        // GET: /Home/

        public ActionResult home()
        {
            return View();
        }

    }
}

MvcTrainingStart/MvcTrainingStart/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MvcTrainingStart.Controllers
{
    public class ProfileController : Controller
    {
        //
        // GET: /Profile/

        public ActionResult Index()
        {
            return View();
        }

    }
}

MvcTrainingStart/MvcTrainingStart/Views/Gallery/gallery.cshtml
@{
    ViewBag.Title = "gallery";
    Layout = "~/Views/Shared/_profile.cshtml";
}

<h2>View Gallery</h2>

<br /><br />

<img src="@Url.Content("~/Content/images/Chrysanthemum.jpg")" width="200" height="200"/>
<img src="@Url.Content("~/Content/images/Desert.jpg")" width="200" height="200" />
<img src="@Url.Content("~/Content/images/Hydrangeas.jpg")" width="200" height="200" />
<img src="@Url.Content("~/Content/images/Jellyfish.jpg")" width="200" height="200" />
<img src="@Url.Content("~/Content/images/Koala.jpg")" width="200" height="200" />
<img src="@Url.Content("~/Content/images/Lighthouse.jpg")" width="200" height= "200" />
<img src="@Url.Content("~/Content/images/Penguins.jpg")" width="200" height="200" />
<img src="@Url.Content("~/Content/images/Tulips.jpg")" width="200" height="200" />

MvcTrainingStart/MvcTrainingStart/Views/Home/home.cshtml
@{
    ViewBag.Title = "About";
    Layout = "~/Views/Shared/_profile.cshtml";
}

<h2>About</h2>
<br />

<p>
    I am currently working as a Software Developer at Gemini Solutions Pvt Ltd, Udhyog Vihar Phase III , Gurgaon
</p>

MvcTrainingStart/MvcTrainingStart/Views/Shared/_profile.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
</head>
<body>

    <div style="margin-bottom : 30px">
        <a href="@Url.Action("home", "Home")">Home</a>    
        <a href="@Url.Action("Index", "Profile")">About</a>    
        <a href="@Url.Action("gallery", "Gallery")">Gallery</a>    
    </div>

    <div>
        @RenderBody()
    </div>
</body>
</html>